resources:
- repo: self
  clean: true

trigger:
  branches:
    include:
      - refs/heads/master
  paths:
    include:
      - Docker/*
      - BuildDockerImages.yml

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  always: true
  branches:
    include:
      - refs/heads/master

stages:
- stage: docker
  displayName: Build Docker Images
  jobs:
    - job: preview
      displayName: Build Preview Image
      pool:
        name: Hosted Ubuntu 1604
      steps:
        - template: Docker/DockerPipelineTemplate.yml
          parameters:
              containerRegistry: DockerHub
              repository: scrthq/powershell
              dockerFile: Docker/Preview.Dockerfile
              #testFile: Docker/TestPreview.Dockerfile
              tag: preview

    - job: latest
      displayName: Build Latest Image
      pool:
        name: Hosted Ubuntu 1604
      steps:
        - template: Docker/DockerPipelineTemplate.yml
          parameters:
              containerRegistry: DockerHub
              repository: scrthq/powershell
              dockerFile: Docker/Latest.Dockerfile
              testFile: Docker/TestLatest.Dockerfile
              tag: latest
