# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
- repo: self
  clean: true

trigger:
  branches:
    include:
      - refs/heads/master
  paths:
    include:
      - Preview.Dockerfile
      - Latest.Dockerfile
      - BuildDockerImages.yml
      - dockerImageBootstrap.ps1

schedules:
- cron: "0 0 0 1/1 * ? *"
  displayName: Daily midnight build
  always: true
  branches:
    include:
      - refs/heads/master

stages:
- stage: docker
  displayName: Build Docker Images
  jobs:
    - job: preview
      displayName: Build Preview Image
      pool:
        name: Hosted Ubuntu 1604
      steps:
        - task: Docker@2
          displayName: Login to DockerHub
          inputs:
            containerRegistry: DockerHub
            command: login
        - task: Docker@2
          displayName: Build Docker Image
          inputs:
            containerRegistry: DockerHub
            command: buildAndPush
            repository: scrthq/powershell
            Dockerfile: Preview.Dockerfile
            tags: preview
        - task: Docker@2
          displayName: Logout of DockerHub
          inputs:
            command: logout
            containerRegistry: DockerHub

    - job: latest
      displayName: Build Latest Image
      pool:
        name: Hosted Ubuntu 1604
      steps:
        - task: Docker@2
          displayName: Login to Docker Hub
          inputs:
            containerRegistry: DockerHub
            command: login
        - task: Docker@2
          displayName: Build Docker Image
          inputs:
            containerRegistry: DockerHub
            command: buildAndPush
            repository: scrthq/powershell
            Dockerfile: Latest.Dockerfile
            tags: latest
        - task: Docker@2
          displayName: Logout of DockerHub
          inputs:
            command: logout
            containerRegistry: DockerHub
