# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
- repo: self
  clean: true

trigger:
  branches:
    include:
      - refs/heads/master
  paths:
    include:
      - Preview.Dockerfile
      - Latest.Dockerfile
      - Test.Dockerfile
      - BuildDockerImages.yml
      - DockerPipelineTemplate.yml
      - dockerImageBootstrap.ps1
      - build.ps1

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  always: true
  branches:
    include:
      - refs/heads/master

stages:
- stage: docker
  displayName: Build Docker Images
  jobs:
    - job: preview
      displayName: Build Preview Image
      pool:
        name: Hosted Ubuntu 1604
      steps:
        - template: DockerPipelineTemplate.yml
          parameters:
              containerRegistry: DockerHub
              repository: scrthq/powershell
              dockerFile: Preview.Dockerfile
              testFile: TestPreview.Dockerfile
              tag: preview

    - job: latest
      displayName: Build Latest Image
      pool:
        name: Hosted Ubuntu 1604
      steps:
        - template: DockerPipelineTemplate.yml
          parameters:
              containerRegistry: DockerHub
              repository: scrthq/powershell
              dockerFile: Latest.Dockerfile
              testFile: TestLatest.Dockerfile
              tag: latest
