parameters:
  MkDocs: ''
  GitUrl: ''

stages:
- stage: Build
  jobs:
  - job: Job1
    displayName: Compile Module
    pool:
      name: Hosted VS2017

    steps:
    - checkout: self
      submodules: recursive

    - powershell: . ./build.ps1
      displayName: Compile Module

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Compiled Module'
      inputs:
        PathtoPublish: BuildOutput
        ArtifactName: BuildOutput

- stage: Test
  jobs:
  - job: Job2
    displayName: Test Windows (PSv5)
    condition: succeeded()
    pool:
      name: Hosted VS2017

    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: BuildOutput
        downloadPath: '$(Build.SourcesDirectory)'

    - powershell: . ./build.ps1 -Task Test
      displayName: Test Module
      env:
        PSGSuiteConfigJson: '$(PSGSuiteConfigJson)'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/Test*.xml'
      inputs:
        testRunner: NUnit
        testResultsFiles: '**/Test*.xml'
      condition: succeededOrFailed()

  - job: Job3
    displayName: Test Ubuntu
    condition: succeeded()
    pool:
      name: Hosted Ubuntu 1604

    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: BuildOutput
        downloadPath: '$(Build.SourcesDirectory)'

    - pwsh: . ./build.ps1 -Task Test
      displayName: Test Module
      env:
        PSGSuiteConfigJson: '$(PSGSuiteConfigJson)'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/Test*.xml'
      inputs:
        testRunner: NUnit
        testResultsFiles: '**/Test*.xml'
      condition: succeededOrFailed()

  - job: Job4
    displayName: Test macOS
    condition: succeeded()
    pool:
      name: Hosted macOS

    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: BuildOutput
        downloadPath: '$(Build.SourcesDirectory)'

    - pwsh: . ./build.ps1 -Task Test
      displayName: Test Module
      env:
        PSGSuiteConfigJson: '$(PSGSuiteConfigJson)'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/Test*.xml'
      inputs:
        testRunner: NUnit
        testResultsFiles: '**/Test*.xml'
      condition: succeededOrFailed()

  - job: Job5
    displayName: Test Windows (PSv6)
    condition: succeeded()
    pool:
      name: Hosted VS2017

    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: BuildOutput
        downloadPath: '$(Build.SourcesDirectory)'

    - pwsh: . ./build.ps1 -Task Test
      displayName: Test Module
      env:
        PSGSuiteConfigJson: '$(PSGSuiteConfigJson)'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/Test*.xml'
      inputs:
        testRunner: NUnit
        testResultsFiles: '**/Test*.xml'
      condition: succeededOrFailed()

  - job: Job6
    displayName: Test Docker (pwsh-preview)
    condition: succeeded()
    pool:
      name: Hosted Ubuntu 1604

    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: BuildOutput
        downloadPath: '$(Build.SourcesDirectory)'

    - pwsh: |
        if (-not (Test-Path Dockerfile)) {
            Write-Host "Pulling Dockerfile from template repo"
            Invoke-RestMethod 'https://raw.githubusercontent.com/SCRT-HQ/AzurePipelineTemplates/master/BuildTestDeployModule/Dockerfile' | Set-Content Dockerfile -Force
        }
        else {
            Write-Host "Dockerfile already exists in current repo! Contents:`n"
            Get-Content Dockerfile
        }
      displayName: Create Dockerfile

    - script: docker build . -t test -f Dockerfile
      displayName: Build container image

    - script: docker run --name test test
      displayName: Test Module in Container

    - script: docker cp test:/source/BuildOutput/TestResults.xml BuildOutput/TestResults.xml
      displayName: Copy container test results

    - script: docker container prune -f
      displayName: Clean up container

    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/Test*.xml'
      condition: succeededOrFailed()
      inputs:
        testRunner: NUnit
        testResultsFiles: '**/Test*.xml'

- stage: Deploy
  jobs:
  - job: Job7
    displayName: Deploy Module
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      name: Hosted VS2017

    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      condition: startsWith(variables['Build.SourceVersionMessage'], '!deploy')
      inputs:
        artifactName: BuildOutput
        downloadPath: '$(Build.SourcesDirectory)'

    - powershell: . ./build.ps1 -Task Deploy
      displayName: Deploy to PowerShell Gallery
      condition: startsWith(variables['Build.SourceVersionMessage'], '!deploy')
      env:
        PSGSuiteConfigJson: '$(PSGSuiteConfigJson)'
        GitHubPAT: $(GitHub.PAT)
        NuGetApiKey: $(NuGetApiKey)
        TwitterAccessSecret: $(Twitter.AccessSecret)
        TwitterAccessToken: $(Twitter.AccessToken)
        TwitterConsumerKey: $(Twitter.ConsumerKey)
        TwitterConsumerSecret: $(Twitter.ConsumerSecret)

- stage: Docs
  jobs:
  - job: Job8
    displayName: Deploy Docs
    condition: and(succeeded(), ne('${{ parameters.MkDocs }}', ''), ne('${{ parameters.GitUrl }}', ''), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      name: Hosted Ubuntu 1604

    steps:
    - checkout: self
      submodules: recursive
      persistCredentials: true

    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: BuildOutput
        downloadPath: '$(Build.SourcesDirectory)'

    - task: DownloadSecureFile@1
      inputs:
        secureFile: deploy_key
      displayName: 'Download Deploy Key'

    - task: UsePythonVersion@0
      inputs:
        addToPath: true
        versionSpec: '2.x'

    - script: pip install --upgrade pip
      displayName: Upgrade pip

    - script: |
        pip install --user mkdocs
        pip install --user mkdocs-material
        pip install --user mkdocs-minify-plugin
      displayName: Install Requirements

    - script: |
        git config --local user.name "Azure Pipelines"
        git config --local user.email "azuredevops@microsoft.com"
        mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
        chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        git remote set-url origin ${{ parameters.GitUrl }}
      displayName: Configure Git

    - powershell: . ./build.ps1 -Task MkDocs
      displayName: Deploy Docs to GitHub Pages
      env:
        GitHubPAT: $(GitHub.PAT)
